Repository FC-SharedOffice-5/BE_SharedOffice, pull requests merged in 2024-06, with the labels that each got.

#56 Feature/#45 일정 관련 개발
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/dto/request/AttendeesRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/dto/response/AttendeesResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/entity/Attendees.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/repository/AttendeesRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/controller/EventController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/entity/Event.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/repository/EventRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/service/EventService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/controller/PlaceController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/schedule/controller/ScheduleController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/schedule/dto/request/ScheduleRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/schedule/dto/request/ScheduleUpdateRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/schedule/dto/response/ScheduleListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/schedule/dto/response/ScheduleResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/schedule/entity/Schedule.java
  src/main/java/com/FC/SharedOfficePlatform/domain/schedule/exception/ScheduleNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/schedule/service/ScheduleService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
Labels: feat

#59 Feature/#58 회의실/스튜디오(장소) 예약 기능 구현
  src/main/java/com/FC/SharedOfficePlatform/domain/office/controller/OfficeController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/repository/OfficeRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/service/OfficeService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/controller/PlaceController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/PlaceFloorStats.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/request/PlaceRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/response/PlaceListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/response/PlaceResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/entity/Place.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/repository/PlaceRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/service/PlaceService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/controller/PlaceReservationController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/dto/request/PlaceReservationRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/dto/response/PlaceReservationListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/dto/response/PlaceReservationResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/entity/PlaceReservation.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/entity/PlaceReservationRequestEntity.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/exception/PlaceReservationNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/repository/PlaceReservationRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/repository/PlaceReservationRequestRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/service/PlaceReservationService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/controller/ReservationController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/entity/Reservation.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/service/ReservationService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
Labels: feat, fix

#61 Feature/#60 코드 리펙토링 및 패키지 구조 변경
  src/main/java/com/FC/SharedOfficePlatform/domain/business/controller/BusinessController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/document/controller/DocumentController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/inquiry/controller/InquiryMyPageController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/controller/PlaceReservationController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/controller/PlaceReservationMyPageController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/service/PlaceReservationService.java
Labels: fix

#63 Feature/#62 좌석 예약 기능
  src/main/java/com/FC/SharedOfficePlatform/domain/seat/controller/SeatController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seat/dto/request/SeatRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seat/dto/response/SeatListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seat/dto/response/SeatResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seat/entity/Seat.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seat/exception/SeatNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seat/repository/SeatRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seat/service/SeatService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/controller/SeatReservationController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/controller/SeatReservationMyPageController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/dto/request/SeatReservationRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/dto/response/SeatReservationDeatilResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/dto/response/SeatReservationListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/dto/response/SeatReservationResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/entity/SeatReservation.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/exception/SeatReservationNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/repository/SeatReservationRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/seatReservation/service/SeatReservationService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
Labels: feat

#65 Feature/#64 장소 예약 기능 리팩토링
  src/main/java/com/FC/SharedOfficePlatform/domain/place/repository/PlaceRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/controller/PlaceReservationController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/controller/PlaceReservationMyPageController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/repository/PlaceReservationRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/placeReservation/service/PlaceReservationService.java
Labels: fix

#77 파일 이미지 업로드 API
  src/main/java/com/FC/SharedOfficePlatform/domain/image/controller/ImageDataController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/dto/ImageDataResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/entity/ImageData.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/exception/ImageFileAlreadyRegisteredException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/exception/ImageFileNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/repository/ImageDataRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/service/ImageDataService.java
  src/main/java/com/FC/SharedOfficePlatform/global/config/FileUploadConfig.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/SecurityConfig.java
  src/main/java/com/FC/SharedOfficePlatform/global/util/ImageUtils.java
  src/main/java/com/FC/SharedOfficePlatform/global/util/TomcatCustomizer.java
  src/main/resources/application.yml
Labels: feat

#81 Feature/#66 자유게시판 기능 개발
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/controller/FreeBoardController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/dto/request/FreeBoardRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/dto/response/FreeBoardDetailResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/dto/response/FreeBoardListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/dto/response/FreeBoardResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/entity/FreeBoard.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/exception/FreeBoardNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/repository/FreeBoardRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/service/FreeBoardService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/memberLike/controller/MemberLikeController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/memberLike/dto/request/MemberLikeRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/memberLike/dto/response/MemberLikeResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/memberLike/entity/MemberLike.java
  src/main/java/com/FC/SharedOfficePlatform/domain/memberLike/exception/MemberLikeNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/memberLike/repository/MemberLikeRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/memberLike/service/MemberLikeService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
Labels: feat

#82 Feature/#80 댓글 기능
  src/main/java/com/FC/SharedOfficePlatform/domain/comment/controller/CommentController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/comment/dto/response/CommentListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/comment/entity/Comment.java
  src/main/java/com/FC/SharedOfficePlatform/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/comment/repository/CommentRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/comment/service/CommentService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/dto/response/FreeBoardDetailResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/dto/response/FreeBoardListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/repository/FreeBoardRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/service/FreeBoardService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
Labels: feat, fix

#84 #83 파일 이미지 API - 멤버에 해당하는 이미지 등록, 조회 API
  src/main/java/com/FC/SharedOfficePlatform/domain/image/controller/ImageDataController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/dto/ImageDataResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/entity/ImageData.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/repository/ImageDataRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/service/ImageDataService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/entity/Member.java
Labels: feat

#87 Feature/#86 - 이미지 조회 - 게시판 사진 조회API #86
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/entity/FreeBoard.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/controller/ImageDataController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/dto/ImageDataResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/entity/ImageData.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/exception/FreeBoardNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/repository/ImageDataRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/service/ImageDataService.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/SecurityConfig.java
Labels: feat

#92 Feature/#91 오피스 이미지 조회 API
  src/main/java/com/FC/SharedOfficePlatform/domain/image/controller/ImageDataController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/dto/ImageDataResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/entity/ImageData.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/exception/OfficeNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/repository/ImageDataRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/image/service/ImageDataService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/entity/Office.java
Labels: feat

#97 feature/#95 자유게시판 닉네임 조회, 오피스명 조회
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/dto/response/FreeBoardDetailResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/dto/response/FreeBoardListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/dto/response/FreeBoardResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/repository/FreeBoardRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/freeBoard/service/FreeBoardService.java
Labels: feat, fix

#101 feature/#100 배열 콤마 형태로 출력
  src/main/java/com/FC/SharedOfficePlatform/domain/office/dto/response/OfficeResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/entity/Office.java
Labels: fix
