Repository FC-SharedOffice-5/BE_SharedOffice, pull requests merged in 2024-05, with the labels that each got.

#4 Feature/#1 : 프로젝트 초기 관련 설정 파일 추가 - application.yml , Git pr / issue template #1
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  src/main/resources/application.yml
Labels: feat

#8 Feature/#5 - feat : 각 도메인 별 패키지 구조 밑작업
  src/main/java/com/FC/SharedOfficePlatform/domain/alarm/controller/AlarmController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/alarm/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/alarm/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/alarm/entity/Alarm.java
  src/main/java/com/FC/SharedOfficePlatform/domain/alarm/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/alarm/service/AlarmService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/controller/AttendeesController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/entity/Attendees.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/repository/AttendeesRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/attendees/service/AttendeesService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/controller/AuthController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/service/AuthService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/controller/BusinessController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/entity/Business.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/repository/BusinessRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/service/BusinessService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/controller/EventController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/entity/Event.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/repository/EventRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/event/service/EventService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/controller/MemberController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/entity/Member.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/exception/MemberAlreadyRegisteredException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/repository/MemberRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/service/MemberService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/controller/OfficeController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/entity/Office.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/repository/OfficeRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/service/OfficeService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/controller/PlaceController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/entity/Place.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/repository/PlaceRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/service/PlaceService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/controller/ReservationController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/entity/Reservation.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/reservation/service/ReservationService.java
Labels: feat

#25 Feature/#23 createdAt, modifiedAt 저장 문제 해결
  src/main/java/com/FC/SharedOfficePlatform/global/common/BaseTimeEntity.java
  src/main/java/com/FC/SharedOfficePlatform/global/config/JpaAuditorConfig.java
  src/main/java/com/FC/SharedOfficePlatform/global/config/SecurityConfig.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/GlobalExceptionRestAdvice.java
Labels: fix

#27 스프링 시큐리티 JWT 설정 개편, 멤버 도메인 수정 + 회원가입, 로그인API 수정 + 로그아웃API 추가 #21
  build.gradle
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/controller/AuthController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/dto/TokenDTO.java
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/exception/MemberNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/auth/service/AuthService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/controller/MemberController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/request/SignUpMemberRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/response/SignUpMemberResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/entity/Member.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/exception/UnauthorizedException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/service/MemberService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/CookieUtils.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/JwtService.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/MemberDetails.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/MemberDetailsService.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/SecurityConfig.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/UnauthorizedHandler.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/enums/AuthorityCode.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/enums/Role.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/jwt/JwtFilter.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/jwt/JwtProvider.java
Labels: feat, fix

#29 POST /email/send/code 인증번호 전송 API 구현
  .gitignore
  build.gradle
  src/main/java/com/FC/SharedOfficePlatform/domain/member/controller/EmailController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/request/SendEmailRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/service/EmailService.java
  src/main/java/com/FC/SharedOfficePlatform/global/config/JavaMailConfig.java
  src/main/resources/application.yml
Labels: feat

#34 Feature/#26 입점 기업 기능 구현
  src/main/java/com/FC/SharedOfficePlatform/domain/business/controller/BusinessController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/dto/request/BusinessRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/dto/response/BusinessListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/dto/response/BusinessResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/entity/Business.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/exception/BusinessNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/repository/BusinessRepository.java
  src/main/java/com/FC/SharedOfficePlatform/domain/business/service/BusinessService.java
  src/main/java/com/FC/SharedOfficePlatform/domain/inquiry/controller/InquiryController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/inquiry/dto/response/InquiryListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/inquiry/service/InquiryService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
Labels: feat

#36 Feature/#35 오피스 지점 관련 구현 및 수정
  src/main/java/com/FC/SharedOfficePlatform/domain/office/controller/OfficeController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/dto/request/OfficeRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/dto/response/OfficeListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/dto/response/OfficeResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/entity/Office.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/exception/OfficeNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/office/service/OfficeService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
  src/test/java/com/FC/SharedOfficePlatform/SharedOfficePlatformApplicationTests.java
Labels: feat, fix

#32 비밀번호 찾기(수정) /members/update/pw/{id} 구현
  src/main/java/com/FC/SharedOfficePlatform/domain/member/controller/MemberController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/request/UpdatePasswordRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/response/SignUpMemberResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/response/UpdatePasswordResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/entity/Member.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/exception/AlreadyUsedPasswordException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/service/MemberService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/SecurityConfig.java
Labels: feat

#42 Feature/#37 회의실/스튜디오 장소 관련 구현 및 수정
  src/main/java/com/FC/SharedOfficePlatform/domain/office/dto/OfficeDto.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/controller/PlaceController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/request/PlaceRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/request/request.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/response/PlaceListResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/response/PlaceResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/dto/response/response.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/entity/Place.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/exception/PlaceNotFoundException.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/exception/exception.java
  src/main/java/com/FC/SharedOfficePlatform/domain/place/service/PlaceService.java
  src/main/java/com/FC/SharedOfficePlatform/global/exception/ErrorCode.java
Labels: feat, fix

#46 회원 ~ 이메일 기능 관련 수정 (오류 수정 및 필드 추가) #38
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/request/SendEmailRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/request/UpdatePasswordRequest.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/entity/Member.java
  src/main/java/com/FC/SharedOfficePlatform/global/security/SecurityConfig.java
Labels: refactor

#51 마이페이지 GET mypage/info/{memberId} 내정보 조회 API
  src/main/java/com/FC/SharedOfficePlatform/domain/member/controller/MyPageController.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/dto/response/MyInfoResponse.java
  src/main/java/com/FC/SharedOfficePlatform/domain/member/service/MyPageService.java
Labels: feat
